In [1]:
import pandas as pd
import json
import os
import pymysql

In [11]:
path1="C:/Users/jayap/soundar/phonepay/pulse/data/aggregated/transaction/country/india/state/"
agg_states_list=os.listdir(path1)


clm1={'State':[],'Year':[],'Quater':[],'Transaction_type':[],'Transaction_count':[],'Transaction_amount':[]}

for states in agg_states_list:
  p_i=path1+states+"/"
  agg_year=os.listdir(p_i)

  for years in agg_year:
    p_j=p_i+years+"/"
    agg_qua=os.listdir(p_j)

    for files in agg_qua:
      p_k=p_j+files
      data=open(p_k,'r')
      a=json.load(data)
      for i in a['data']['transactionData']:
        Name=i['name']
        count=i['paymentInstruments'][0]['count']
        amount=i['paymentInstruments'][0]['amount']
        clm1['State'].append(states)
        clm1['Year'].append(years)
        clm1['Quater'].append(int(files.strip('.json')))
        clm1['Transaction_type'].append(Name)
        clm1['Transaction_count'].append(count)
        clm1['Transaction_amount'].append(amount)

agg_trans=pd.DataFrame(clm1)
agg_trans["State"] = agg_trans["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
agg_trans["State"] = agg_trans["State"].str.replace("-"," ")
agg_trans["State"] = agg_trans["State"].str.title()
agg_trans['State'] = agg_trans['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [3]:
path2="C:/Users/jayap/soundar/phonepay/pulse/data/aggregated/user/country/india/state/"
agg_user_list=os.listdir(path2)


clm2={'State':[],'Year':[],'Quater':[],'Brand':[],'Transaction_count':[],'percentage':[]}

for states in agg_user_list:
  p_i=path2+states+"/"
  agg_year=os.listdir(p_i)

  for years in agg_year:
    p_j=p_i+years+"/"
    agg_qua=os.listdir(p_j)

    for files in agg_qua:
      p_k=p_j+files
      data=open(p_k,'r')
      b=json.load(data)

      try:

        for i in b["data"]["usersByDevice"]:
          brand=i['brand']
          count=i['count']
          percentage=i['percentage']
          clm2['State'].append(states)
          clm2['Year'].append(years)
          clm2['Quater'].append(int(files.strip('.json')))
          clm2['Brand'].append(brand)
          clm2['Transaction_count'].append(count)
          clm2['percentage'].append(percentage)

      except:
        pass
agg_users=pd.DataFrame(clm2)
agg_users["State"] = agg_users["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
agg_users["State"] = agg_users["State"].str.replace("-"," ")
agg_users["State"] = agg_users["State"].str.title()
agg_users['State'] = agg_users['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [4]:
path3="C:/Users/jayap/soundar/phonepay/pulse/data/map/transaction/hover/country/india/state/"
map_trans_list=os.listdir(path3)


clm3={'State':[],'Year':[],'Quater':[],'District':[],'Transaction_count':[],'Transaction_amount':[]}

for states in map_trans_list:
  p_i=path3+states+"/"
  agg_year=os.listdir(p_i)

  for years in agg_year:
    p_j=p_i+years+"/"
    agg_qua=os.listdir(p_j)

    for files in agg_qua:
      p_k=p_j+files
      data=open(p_k,'r')
      c=json.load(data)

      for i in c["data"]["hoverDataList"]:
        district=i['name']
        count=i['metric'][0]['count']
        amount=i['metric'][0]['amount']
        clm3['State'].append(states)
        clm3['Year'].append(years)
        clm3['Quater'].append(int(files.strip('.json')))
        clm3['District'].append(district)
        clm3['Transaction_count'].append(count)
        clm3['Transaction_amount'].append(amount)


map_trans=pd.DataFrame(clm3)
map_trans["State"] = map_trans["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_trans["State"] = map_trans["State"].str.replace("-"," ")
map_trans["State"] = map_trans["State"].str.title()
map_trans['State'] = map_trans['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [5]:
path4="C:/Users/jayap/soundar/phonepay/pulse/data/map/user/hover/country/india/state/"
map_user_list=os.listdir(path4)


clm4={'State':[],'Year':[],'Quater':[],'District':[],'RegisteredUsers':[],'Appopens':[]}

for states in map_user_list:
  p_i=path4+states+"/"
  agg_year=os.listdir(p_i)

  for years in agg_year:
    p_j=p_i+years+"/"
    agg_qua=os.listdir(p_j)

    for files in agg_qua:
      p_k=p_j+files
      data=open(p_k,'r')
      d=json.load(data)

      for i in d["data"]["hoverData"].items():
        district=i[0]
        count=i[1]["registeredUsers"]
        appopen=i[1]['appOpens']
        clm4['State'].append(states)
        clm4['Year'].append(years)
        clm4['Quater'].append(int(files.strip('.json')))
        clm4['District'].append(district)
        clm4['RegisteredUsers'].append(count)
        clm4['Appopens'].append(appopen)


map_users=pd.DataFrame(clm4)
map_users["State"] = map_users["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_users["State"] = map_users["State"].str.replace("-"," ")
map_users["State"] = map_users["State"].str.title()
map_users['State'] = map_users['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [2]:
path5="C:/Users/jayap/soundar/phonepay/pulse/data/top/transaction/country/india/state/"
top_trans_list=os.listdir(path5)


clm5={'State':[],'Year':[],'Quater':[],'Pincode':[],'Transaction_count':[],'Transaction_amount':[]}

for states in top_trans_list:
  p_i=path5+states+"/"
  agg_year=os.listdir(p_i)

  for years in agg_year:
    p_j=p_i+years+"/"
    agg_qua=os.listdir(p_j)

    for files in agg_qua:
      p_k=p_j+files
      data=open(p_k,'r')
      e=json.load(data)

      for i in e["data"]["pincodes"]:
        pincode=str(i["entityName"])
        count=i["metric"]["count"]
        amount=i["metric"]["amount"]
        clm5['State'].append(states)
        clm5['Year'].append(years)
        clm5['Quater'].append(int(files.strip('.json')))
        clm5['Pincode'].append(pincode)
        clm5['Transaction_count'].append(count)
        clm5['Transaction_amount'].append(amount)


top_trans=pd.DataFrame(clm5)
top_trans["State"] = top_trans["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_trans["State"] = top_trans["State"].str.replace("-"," ")
top_trans["State"] = top_trans["State"].str.title()
top_trans['State'] = top_trans['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [3]:
path6="C:/Users/jayap/soundar/phonepay/pulse/data/top/user/country/india/state/"
top_users_list=os.listdir(path6)


clm6={'State':[],'Year':[],'Quater':[],'Pincode':[],'RegisteredUsers':[]}

for states in top_users_list:
  p_i=path6+states+"/"
  agg_year=os.listdir(p_i)

  for years in agg_year:
    p_j=p_i+years+"/"
    agg_qua=os.listdir(p_j)

    for files in agg_qua:
      p_k=p_j+files
      data=open(p_k,'r')
      e=json.load(data)

      for i in e["data"]["pincodes"]:
        pincode=str(i["name"])
        count=i["registeredUsers"]
        clm6['State'].append(states)
        clm6['Year'].append(years)
        clm6['Quater'].append(int(files.strip('.json')))
        clm6['Pincode'].append(pincode)
        clm6['RegisteredUsers'].append(count)


top_users=pd.DataFrame(clm6)
top_users["State"] = top_users["State"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_users["State"] = top_users["State"].str.replace("-"," ")
top_users["State"] = top_users["State"].str.title()
top_users['State'] = top_users['State'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [4]:
myconnection = pymysql.connect(host='localhost',user='root',passwd='Soundar@2003',database='phonepay')
cur = myconnection.cursor()

In [13]:
cur.execute('''drop table if exists aggregated_trans''')
myconnection.commit()

cur.execute('''create table if not exists aggregated_trans(state text,
            year int,
            quater int,
            transaction_type text,
            transaction_count bigint,
            transaction_amount bigint)''')
myconnection.commit()

sql = "insert into aggregated_trans(state,year,quater,transaction_type,transaction_count,transaction_amount) values (%s,%s,%s,%s,%s,%s)"

for i in range(0,len(agg_trans)):
    cur.execute(sql,tuple(agg_trans.iloc[i]))
    myconnection.commit()

In [13]:
cur.execute('''drop table if exists aggregated_users''')
myconnection.commit()

cur.execute('''create table if not exists aggregated_users(state text,
            year int,
            quater int,
            brand text,
            transaction_count bigint,
            percentage float)''')
myconnection.commit()

sql = "insert into aggregated_users(state,year,quater,brand,transaction_count,percentage) values (%s,%s,%s,%s,%s,%s)"

for i in range(0,len(agg_users)):
    cur.execute(sql,tuple(agg_users.iloc[i]))
    myconnection.commit()

In [15]:
cur.execute('''drop table if exists map_transa''')
myconnection.commit()

cur.execute('''create table if not exists map_transa(state text,
            year int,
            quater int,
            district text,
            transaction_count bigint,
            transaction_amount bigint)''')
myconnection.commit()

sql = "insert into map_transa(state,year,quater,district,transaction_count,transaction_amount) values (%s,%s,%s,%s,%s,%s)"

for i in range(0,len(map_trans)):
    cur.execute(sql,tuple(map_trans.iloc[i]))
    myconnection.commit()

In [15]:
cur.execute('''drop table if exists map_user''')
myconnection.commit()

cur.execute('''create table if not exists map_user(state text,
            year int,
            quater int,
            district text,
            registered_users bigint,
            appopens bigint)''')
myconnection.commit()

sql = "insert into map_user(state,year,quater,district,registered_users,appopens) values (%s,%s,%s,%s,%s,%s)"

for i in range(0,len(map_users)):
    cur.execute(sql,tuple(map_users.iloc[i]))
    myconnection.commit()

In [5]:
cur.execute('''drop table if exists top_transa''')
myconnection.commit()

cur.execute('''create table if not exists top_transa(state text,
            year int,
            quater int,
            pincode varchar(10),
            transaction_count bigint,
            transaction_amount bigint)''')
myconnection.commit()

sql = "insert into top_transa(state,year,quater,pincode,transaction_count,transaction_amount) values (%s,%s,%s,%s,%s,%s)"

for i in range(0,len(top_trans)):
    cur.execute(sql,tuple(top_trans.iloc[i]))
    myconnection.commit()

In [ ]:
cur.execute('''drop table if exists top_user''')
myconnection.commit()

cur.execute('''create table if not exists top_user(state text,
            year int,
            quater int,
            pincode varchar(10),
            registered_users bigint)''')
myconnection.commit()

sql = "insert into top_user(state,year,quater,pincode,registered_users) values (%s,%s,%s,%s,%s)"

for i in range(0,len(top_users)):
    cur.execute(sql,tuple(top_users.iloc[i]))
    myconnection.commit()